# Generated by Django 3.1.5 on 2021-01-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Date',
            field=models.DateTimeField(blank=True),
        ),
    ]
