# Generated by Django 3.1.5 on 2021-03-11 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210310_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Price',
        ),
    ]
