# Generated by Django 3.1.5 on 2021-03-18 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='PriceModel',
        ),
        migrations.AddField(
            model_name='pricing',
            name='Currency',
            field=models.CharField(blank=True, choices=[('US', 'USD'), ('CA', 'CAD')], default='CA', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='Label',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='Name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
